name: ramp-supercondictivty-temperature
channels:
  - conda-forge
dependencies:
  - joblib
  - matplotlib
  - numpy
  - pandas
  - scikit-learn>=1.4
  - ucimlrepo
  - pip
  - pip:
    - ramp-workflow
